sudo: required

language: python

python:
  - '2.7'

addons:
  apt:
    packages:
      - sshpass

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - python tests.py

before_install:
  - docker --version
  - docker build -t $DOCKER_USERNAME/simple_flask_app:latest .
  - docker images
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy_key.enc -out ./deploy_key -d

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/simple_flask_app:latest
  - export SSHPASS=$DEPLOY_PASS

deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && sshpass -e ssh -o StrictHostKeyChecking=no -i ./deploy_key
    uksdocker@147.91.177.194 './deploy.sh'
  on:
    branch: master
