sudo: true

language: python

python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install -r myapp/requirements.txt

script:
  - python myapp/tests.py
  - docker --version
  - docker build -t simple_flask_app -f myapp/Dockerfile .
  - docker images
  - docker run -d -p 5000:5000 simple_flask_app
  - curl localhost:5000
