sudo: required

language: python

python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - python tests.py

before_install:
  - docker --version
  - docker build -t $DOCKER_USERNAME/simple_flask_app:latest .
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/simple_flask_app:latest
    chmod 600 $DEPLOY_KEY && ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY $HOST_NAME@$HOST_IP ./deploy.sh
    echo "done :)))"
    fi
