sudo: required

language: python

python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - python tests.py

before_install:
  - docker --version
  - docker build -t $DOCKER_USERNAME/simple_flask_app:latest .
  - docker images

after_success:
  - docker run -d -p 5000:5000 $DOCKER_USERNAME/simple_flask_app:latest
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/simple_flask_app:latest
  - "curl -o - -I http://0.0.0.0:5000"
