apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    app: flask
